# app/services/turnstile_service.py
"""
Cloudflare Turnstile Service
-----------------------------
Verifies Turnstile challenge tokens to prevent bot attacks and automated abuse.

Cloudflare Turnstile is a user-friendly CAPTCHA alternative that runs invisibly
in most cases, only challenging suspicious requests.
"""

import requests
from typing import Dict, Any, Optional
from flask import current_app, request

from app.core.config import get_settings


class TurnstileService:
    """
    Service for verifying Cloudflare Turnstile challenge responses.

    Turnstile provides bot protection without degrading user experience.
    It works by verifying a token generated by the frontend widget against
    Cloudflare's verification API.

    Usage:
        # In endpoint
        if not TurnstileService.verify_token(request.form.get('cf-turnstile-response')):
            return error_response("Bot verification failed", 403)

        # Using decorator
        @require_turnstile()
        def login():
            # Token already verified by decorator
            pass
    """

    @staticmethod
    def is_enabled() -> bool:
        """
        Check if Turnstile verification is enabled.

        Returns:
            True if enabled in settings, False otherwise

        Note:
            Typically disabled in development/testing environments
        """
        settings = get_settings()
        return settings.TURNSTILE_ENABLED

    @staticmethod
    def verify_token(
        token: Optional[str],
        remote_ip: Optional[str] = None
    ) -> bool:
        """
        Verify Turnstile challenge token with Cloudflare API.

        Args:
            token: Turnstile response token from frontend widget
            remote_ip: Client IP address (optional, extracted from request if not provided)

        Returns:
            True if verification succeeds, False otherwise

        Security:
            - Returns True if Turnstile is disabled (dev/test mode)
            - Returns False if token is missing or invalid
            - Extracts real IP considering reverse proxy headers
            - Timeout prevents hanging on slow verification requests
            - Logs verification failures for security monitoring

        Example:
            >>> token = request.form.get('cf-turnstile-response')
            >>> if TurnstileService.verify_token(token):
            ...     # Process request
            ... else:
            ...     return error_response("Verification failed", 403)
        """
        settings = get_settings()

        # Skip verification if disabled (development/testing)
        if not settings.TURNSTILE_ENABLED:
            current_app.logger.debug("Turnstile verification skipped (disabled)")
            return True

        # Reject if no token provided
        if not token:
            current_app.logger.warning("Turnstile token missing")
            return False

        # Extract real IP (considering reverse proxy headers)
        if remote_ip is None:
            remote_ip = TurnstileService._get_real_ip()

        # Prepare verification request
        payload = {
            'secret': settings.TURNSTILE_SECRET_KEY,
            'response': token,
            'remoteip': remote_ip,
        }

        try:
            # Send verification request to Cloudflare
            response = requests.post(
                settings.TURNSTILE_VERIFY_URL,
                data=payload,
                timeout=settings.TURNSTILE_TIMEOUT
            )
            response.raise_for_status()

            # Parse verification response
            result = response.json()

            if result.get('success'):
                current_app.logger.info(
                    f"Turnstile verification succeeded for IP: {remote_ip}"
                )
                return True
            else:
                # Log error codes for debugging
                error_codes = result.get('error-codes', [])
                current_app.logger.warning(
                    f"Turnstile verification failed for IP {remote_ip}. "
                    f"Error codes: {error_codes}"
                )
                return False

        except requests.exceptions.Timeout:
            current_app.logger.error(
                f"Turnstile verification timeout ({settings.TURNSTILE_TIMEOUT}s) "
                f"for IP: {remote_ip}"
            )
            # Fail closed: reject on timeout
            return False

        except requests.exceptions.RequestException as e:
            current_app.logger.error(
                f"Turnstile verification request failed: {str(e)}"
            )
            # Fail closed: reject on error
            return False

        except ValueError as e:
            current_app.logger.error(
                f"Turnstile verification response parsing failed: {str(e)}"
            )
            return False

    @staticmethod
    def _get_real_ip() -> str:
        """
        Extract real client IP address from request.

        Considers reverse proxy headers (X-Real-IP, X-Forwarded-For) to get
        the actual client IP when behind nginx or Cloudflare.

        Returns:
            Client IP address as string

        Priority:
            1. X-Real-IP header (set by nginx)
            2. X-Forwarded-For header (first IP in chain)
            3. request.remote_addr (direct connection)
        """
        # Try X-Real-IP first (set by nginx for Cloudflare integration)
        real_ip = request.headers.get('X-Real-IP')
        if real_ip:
            return real_ip

        # Try X-Forwarded-For (comma-separated list, take first)
        forwarded_for = request.headers.get('X-Forwarded-For')
        if forwarded_for:
            # First IP is the original client
            return forwarded_for.split(',')[0].strip()

        # Fallback to direct remote address
        return request.remote_addr or '0.0.0.0'

    @staticmethod
    def get_verification_details(token: str) -> Dict[str, Any]:
        """
        Get detailed verification response from Cloudflare (for debugging).

        Args:
            token: Turnstile response token

        Returns:
            Dictionary with verification details:
            {
                'success': bool,
                'challenge_ts': str,  # ISO timestamp
                'hostname': str,      # Domain where challenge was solved
                'error-codes': list,  # Error codes if failed
                'action': str,        # Action name (if configured)
                'cdata': str          # Custom data (if configured)
            }

        Note:
            Use this only for debugging. For production, use verify_token()
            which returns a simple boolean.
        """
        settings = get_settings()

        if not settings.TURNSTILE_ENABLED:
            return {
                'success': True,
                'message': 'Turnstile disabled (development mode)'
            }

        payload = {
            'secret': settings.TURNSTILE_SECRET_KEY,
            'response': token,
            'remoteip': TurnstileService._get_real_ip(),
        }

        try:
            response = requests.post(
                settings.TURNSTILE_VERIFY_URL,
                data=payload,
                timeout=settings.TURNSTILE_TIMEOUT
            )
            response.raise_for_status()
            return response.json()

        except requests.exceptions.RequestException as e:
            return {
                'success': False,
                'error-codes': ['request-failed'],
                'message': str(e)
            }
